apiVersion: v1
entries:
  argocd-cluster-add:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-14T19:23:57.724954048Z"
    description: A Helm chart for Kubernetes
    digest: b126de2f8926093b8d2311e9f9c6d74732150458f7ea81da509d0e2e6311bb88
    name: argocd-cluster-add
    type: application
    urls:
    - https://victorcmsantos.github.io/helms/charts/argocd-cluster-add-0.1.0.tgz
    version: 0.1.0
  certificate:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-14T19:23:57.725634256Z"
    description: A Helm chart for Kubernetes
    digest: a47a5d0d49acf165298dcc6a5e4af6c145eb371a3f9a28b2470a8e7f67a04708
    name: certificate
    type: application
    urls:
    - https://victorcmsantos.github.io/helms/charts/certificate-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-14T19:23:57.725343214Z"
    description: A Helm chart for Kubernetes
    digest: 5684dfb7cee9a39d2510f61a34ac538ea926e49ffad6e4374237696b6ebd106c
    name: certificate
    type: application
    urls:
    - https://victorcmsantos.github.io/helms/charts/certificate-0.1.0.tgz
    version: 0.1.0
  clusterissuer:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-11-14T19:23:57.726160589Z"
    description: A Helm chart for Kubernetes
    digest: fd12356e203ffb22e25632b50c37539f5df29972c3b281f5d44efb299ecf556d
    name: clusterissuer
    type: application
    urls:
    - https://victorcmsantos.github.io/helms/charts/clusterissuer-0.1.0.tgz
    version: 0.1.0
generated: "2024-11-14T19:23:57.724259756Z"
