apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-cluster-secret
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ .Values.name }}
  server: {{ .Values.apiServerEndpoint }}
  config: |
    {
      "bearerToken": "{{ .Values.bearerToken }}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "{{ .Values.caCertificateData }}"
      }
    }